# Generated by Django 4.1.7 on 2023-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='with_price',
            field=models.BooleanField(default=False, verbose_name='con precio'),
        ),
    ]
