# Generated by Django 4.1.7 on 2023-04-03 22:00

import apps.product.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=functools.partial(apps.product.models.get_upload_path_more_images, *(), **{'field_name': 'image'}), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(apps.product.models.get_upload_path, *(), **{'field_name': 'image'}), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='only_attribute',
            field=models.BooleanField(default=False, verbose_name='only_attribute'),
        ),
    ]
