# Generated by Django 4.1.7 on 2023-04-03 22:24

import apps.product.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_images_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='only_attribute',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=functools.partial(apps.product.models.get_upload_path_more_images, *(), **{'field_name': 'more_images'}), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(apps.product.models.get_upload_path, *(), **{'field_name': 'products'}), verbose_name='Imagen'),
        ),
    ]
