# Generated by Django 4.1.7 on 2023-05-05 01:13

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
