# Generated by Django 4.1.7 on 2023-05-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
