# Generated by Django 4.1.7 on 2023-05-09 16:11

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similarity_combined',
            field=models.CharField(blank=True, default=django.db.models.functions.text.Concat('marca', models.Value(' '), 'title', models.Value(' '), 'description', output_field=models.CharField()), editable=False, max_length=300, null=True, verbose_name='Similaridad combinada'),
        ),
    ]
