# Generated by Django 4.1.7 on 2023-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_similarity_combined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='similarity_combined',
        ),
    ]
