# Generated by Django 4.1.7 on 2023-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_similarity_combined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de oferta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
