# Generated by Django 4.1.7 on 2023-04-14 20:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellido')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='pais')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='ciudad')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='estado/provincia')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='direccion')),
                ('apartamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='apartamento')),
                ('codigo_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='codigo postal')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'anonymous user data',
                'verbose_name_plural': 'anonymous user data',
            },
        ),
    ]
