# Generated by Django 4.1.7 on 2023-04-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_alter_anonymouspersonaldata_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouspersonaldata',
            name='apellido',
            field=models.CharField(default='aa', max_length=50, verbose_name='apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouspersonaldata',
            name='direccion',
            field=models.CharField(default='aa', max_length=80, verbose_name='direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouspersonaldata',
            name='email',
            field=models.CharField(default='aa', max_length=100, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouspersonaldata',
            name='nombre',
            field=models.CharField(default='aa', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouspersonaldata',
            name='telefono',
            field=models.CharField(default='aa', max_length=50, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
