# Generated by Django 4.1.7 on 2023-03-14 16:29

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('padre', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='tienda.categoriatienda')),
            ],
            options={
                'verbose_name': 'CategoriaTienda',
                'verbose_name_plural': 'CategoriaTiendas',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('domain', models.CharField(max_length=50, verbose_name='dominio')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('visits', models.IntegerField(default=0, verbose_name='visitas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CategoriaTienda', to='tienda.categoriatienda', verbose_name='CategoriaTienda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='StoreGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=150, null=True, verbose_name='pais')),
                ('region', models.CharField(blank=True, max_length=150, null=True, verbose_name='region')),
                ('subregion', models.CharField(blank=True, max_length=150, null=True, verbose_name='subregion')),
                ('ciudad', models.CharField(blank=True, max_length=150, null=True, verbose_name='ciudad')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='direccion')),
                ('codigo_postal', models.CharField(blank=True, max_length=150, null=True, verbose_name='codigo_postal')),
                ('barrio', models.CharField(blank=True, max_length=150, null=True, verbose_name='barrio')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_tienda', to='tienda.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'Geolozalizacion_geodjango',
                'verbose_name_plural': 'Geolocalizaciones_geodjango',
            },
        ),
    ]
