# Generated by Django 4.1.7 on 2023-03-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriatienda',
            old_name='padre',
            new_name='parent',
        ),
    ]
