# Generated by Django 4.1.7 on 2023-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_padre_categoriatienda_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
    ]
