# Generated by Django 4.1.7 on 2023-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_tienda_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatienda',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
