# Generated by Django 4.1.7 on 2023-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_categoriatienda_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='category',
        ),
        migrations.AddField(
            model_name='tienda',
            name='categories',
            field=models.ManyToManyField(related_name='Tiendas', to='tienda.categoriatienda', verbose_name='CategoriasTienda'),
        ),
    ]
