# Generated by Django 4.1.7 on 2023-03-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_plan_tienda_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='plan',
        ),
    ]
