# Generated by Django 4.1.7 on 2023-03-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_tienda_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda_plan', to='tienda.plan', verbose_name='Plan'),
        ),
    ]
