# Generated by Django 4.1.7 on 2023-03-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_tienda_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='blog_categories',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='blog_entries',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='images_x_entries',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='product_categories',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='services',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='services_categories',
        ),
    ]
