# Generated by Django 4.1.7 on 2023-03-30 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_remove_plan_images_x_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tienda/logo', verbose_name='logo')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='tienda/portada', verbose_name='portada')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Imagen de la tienda',
                'verbose_name_plural': 'Imagenes de la tienda',
            },
        ),
    ]
