# Generated by Django 4.1.7 on 2023-04-03 22:07

import apps.tienda.models
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_tiendaimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaimages',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/mitienda_logo_3_2_512.png', null=True, upload_to=functools.partial(apps.tienda.models.get_upload_path, *(), **{'field_name': 'image'}), verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='tiendaimages',
            name='portada',
            field=models.ImageField(blank=True, default='defaults/portada1.jpg', null=True, upload_to=functools.partial(apps.tienda.models.get_upload_path, *(), **{'field_name': 'image'}), verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='tiendaimages',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienda_images', to='tienda.tienda', verbose_name='Tienda'),
        ),
    ]
