# Generated by Django 4.1.7 on 2023-04-11 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_alter_tiendaimages_logo_alter_tiendaimages_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_tienda', models.CharField(default='store', max_length=5, verbose_name='tipo_tienda')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to='tienda.tienda', verbose_name='Tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
