# Generated by Django 4.1.7 on 2023-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_storesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Configuracion de la tienda', 'verbose_name_plural': 'Configuraciones de las tiendas'},
        ),
        migrations.AddField(
            model_name='storesettings',
            name='mercadopago',
            field=models.BooleanField(default=False, verbose_name='mercadopago'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='only_order',
            field=models.BooleanField(default=True, verbose_name='solo_ordenar'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='transferencia'),
        ),
    ]
