# Generated by Django 4.1.7 on 2023-04-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_storestatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storestatistics',
            options={'verbose_name': 'Estadisticas de la tienda', 'verbose_name_plural': 'Estadisticas de las tiendas'},
        ),
    ]
