# Generated by Django 4.1.7 on 2023-04-19 06:38

import apps.tienda.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_alter_storestatistics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigoqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qr_code', models.ImageField(blank=True, upload_to=functools.partial(apps.tienda.models.get_upload_path, *(), **{'field_name': 'qrcode'}))),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tienda.tienda', verbose_name='tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
