# Generated by Django 4.1.7 on 2023-04-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_codigoqr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoqr',
            options={'verbose_name': 'Codigo QR', 'verbose_name_plural': 'Codigos QR'},
        ),
    ]
