# Generated by Django 4.1.7 on 2023-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_remove_storegeo_barrio_remove_storegeo_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storegeo',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
