# Generated by Django 4.1.7 on 2023-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_storegeo_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='order_email',
            field=models.BooleanField(default=True, verbose_name='orden_email'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='order_wp',
            field=models.BooleanField(default=False, verbose_name='orden_wp'),
        ),
    ]
