# Generated by Django 4.1.7 on 2023-05-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_tiendavisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='wp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='wp_number'),
        ),
    ]
