# Generated by Django 4.1.7 on 2023-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_storesettings_wp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='order_wp',
            field=models.BooleanField(default=True, verbose_name='orden_wp'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='tipo_tienda',
            field=models.CharField(default='order', max_length=5, verbose_name='tipo_tienda'),
        ),
    ]
